image: node:16

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
    stage: build
    before_script:
        - yarn install
    script:
        - yarn docs:build
    artifacts:
        expire_in: 1 weeks
        paths:
            - "docs/.vuepress/dist"

deploy:
    stage: deploy
    dependencies:
        - build
    before_script:
        - echo $CI_SERVER_SHELL_SSH_HOST
        - echo $CI_SERVER_SHELL_SSH_PORT
        - echo $CI_COMMIT_SHORT_SHA
        - eval `ssh-agent -s`
        - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan -p $CI_SERVER_SHELL_SSH_PORT $CI_SERVER_SHELL_SSH_HOST >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - git config --global user.email "admin@mczhengyi.top"
        - git config --global user.name "zhengyi"
    script:
        - git --version
        - echo $GIT_REPO
        - cd docs/.vuepress/dist
        - ls -l
        - git init
        - git checkout -b gh-docs
        - git add .
        - git commit -m 'deploy from ${$CI_COMMIT_SHORT_SHA}'
        - git push -f -u $GIT_REPO gh-docs

deploy_github:
    stage: deploy
    dependencies:
        - build
    script:
        - echo "deploy to github ..."

deploy_gitee:
    stage: deploy
    dependencies:
        - build
    script:
        - echo "deploy to gitee ..."

